// Write pipeline for GitHub + Maven

pipeline {
    agent any

    tools {
        // Install the Maven version configured as "M3" and add it to the path.
        maven "M3"
    }

    stages {
        stage('Fetch Code') {
            steps {
                // Get some code from a GitHub repository
                git 'https://github.com/sivaprasath-p/project-works.git'
            }
        }
            
        stage('Build Code') {
            steps {
                // Change directory
                dir('project-terraform-demo-rsrc/demo1') {
                    // Run Maven on a Unix agent.
                    sh "mvn -Dmaven.test.failure.ignore=true clean package"
                }    
            }

            post {
                // If Maven was able to run the tests, even if some of the test
                // failed, record the test results and archive the jar file.
                success {
                    junit '**/target/surefire-reports/TEST-*.xml'
                    archiveArtifacts 'target/*.jar'
                }
            }
        }
    }
}
